### ISSUE TITLE
Link to example notebook from README.md

### ISSUE THREAD

**Issue by kbarros** [JuliaPluto/PlutoHooks.jl#11]
This HTML page explains how to use PlutoHooks:
https://juliapluto.github.io/PlutoHooks.jl/src/notebook.html

Perhaps it should be linked prominently from the README?

**Comment by Pangoraw** [comment]
We link to this source notebook but are currently lacking proper user facing documentation. Thanks for looking into this!

**Comment by kbarros** [comment]
I see now. I created a PR proposing some README changes to make this more discoverable.

https://github.com/JuliaPluto/PlutoHooks.jl/pull/12
